### ISSUE TITLE
limit of 100 emails?

### ISSUE THREAD

**Issue by boris-noyvert** [TeWu/GmailAttachmentsExtractor#3]
It seems that if the Gmail filter returns more than 100 emails, GmailAttachmentsExtractor only finds and processes the first 100 (latest by date?).

```
java -jar GmailAttachmentsExtractor.jar --min-size 100k -l larger10MB  larger:10M larger10MB

Feb 21, 2021 7:28:26 PM com.google.api.client.util.store.FileDataStoreFactory setPermissionsToOwnerOnly
WARNING: unable to change permissions for everybody: C:\Users\...\GmailAttachmentsExtractor_v1.0.1\tokens
Feb 21, 2021 7:28:26 PM com.google.api.client.util.store.FileDataStoreFactory setPermissionsToOwnerOnly
WARNING: unable to change permissions for owner: C:\Users\...\GmailAttachmentsExtractor_v1.0.1\tokens

Starting Gmail Attachments Extractor v1.0.1
Parameters:
    Query string: larger:10M
    Output directory: C:\Users\...\GmailAttachmentsExtractor_v1.0.1\larger10MB
    Output labels prefix: larger10MB
    Attachment filter:
        File size: min 100,000 bytes
Creating output labels 'larger10MB [pre]' and 'larger10MB [post]'
Query 'larger:10M' matched 100 email messages
1/100 (1%) | Processing email '...'
...
```

But I can see in Gmail that "larger:10M" filter returns ~170 emails.

Thank you!

**Comment by TeWu** [comment]
Thanks! Fixed.

**Comment by boris-noyvert** [comment]
Thank you.
Do I need to compile from source now to make this working without the limit of 100 emails?
Sorry, I am not a java expert...

**Comment by TeWu** [comment]
Yes, you need to use version compiled from source.
I've compiled it for your convenience: [GmailAttachmentsExtractor_v1.0.1.next.zip](https://drive.google.com/file/d/1hRb8bXrRJC84_jtWIrp9Cv-gk9-06CRo/view?usp=sharing) (sha1: `d70133d357d8412ff257fbecd8e50cece7401847`).
I'm gonna make a stable release soon.

**Comment by shyderc** [comment]
> Yes, you need to use version compiled from source.
> I've compiled it for your convenience: [GmailAttachmentsExtractor_v1.0.1.next.zip](https://drive.google.com/file/d/1hRb8bXrRJC84_jtWIrp9Cv-gk9-06CRo/view?usp=sharing) (sha1: `d70133d357d8412ff257fbecd8e50cece7401847`).
> I'm gonna make a stable release soon.

This version gets 500 emails max. (capped by Google?)
I think you need to use pageToken query parameter?

**Comment by shyderc** [comment]
Yes I see that you need to parse the response for string;
 "nextPageToken": "08833573449120401645"
If exists, make a new request with pageToken parameter and pass the value as a string.
If the response has no nextpageToken then you are done.
(If I was a Java programmer...)
